#ifndef TIKTOKGEN_GENERATORREQUIREMENTTYPE_H
#define TIKTOKGEN_GENERATORREQUIREMENTTYPE_H

enum GeneratorRequirementType {
    NONE,
    NEED_VIDEO,
    NEED_TEXT
};


#endif //TIKTOKGEN_GENERATORREQUIREMENTTYPE_H
